#!/bin/bash

aws_completer=$(type -P aws_completer)

if [[ $aws_completer ]]; then
  complete -C "$aws_completer" aws
fi

function install-awscli {
  awscli_src="https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  if uname -m | grep -q aarch64; then
    awscli_src="https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip"
  fi
  ( if cd "$TMP"; then
      echo >&2 "Downloading $awscli_src in $TMP"
      curl -cfsSL "$awscli_src" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install --update
      aws --version
    fi
  )
}

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-list-aws_cli_auto_prompt
export AWS_CLI_AUTO_PROMPT='on-partial'
export AWS_DEFAULT_OUTPUT='json'
# export AWS_DEFAULT_REGION='eu-central-1'
