#!/bin/bash

aws_completer=$(type -P aws_completer)

if [[ $aws_completer ]]; then
  complete -C "$aws_completer" aws
fi

function install-awscli {
  TMP=$(mktemp -d)
  if cd "$TMP"; then
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  fi
}
