#!/bin/bash

AWS_SSO_CACHE="$XDG_CACHE_HOME/aws-sso-profile"

aws-sso-profile() {
  local account="$1"
  local profile
  if [[ -z $account ]]; then
    if account=$(git rev-parse --show-toplevel); then
      account="${account##*/}"
      account="${account##*tec-}"
      remainder="${account#*-*-}"
      account="${account%-"$remainder"}"
      account="tec-$account-${PWD##*/}"
    else
      account=$(
        source "$AWS_SSO_CACHE"
        echo "$AWS_SSO_PROFILE"
      )
    fi
  fi

  profile=$(aws-sso list | awk -v account="$account" '$0 ~ account{ print $7 }')

  if (($(wc -l <<<"$profile") > 1)); then
    echo >&2 "WARNING: Multiple profiles found for '$account'"
    echo >&2 "$profile"
    profile=$(
      for p in TEC Administrator admin TestProd; do
        grep -Ei "$p" <<<"$profile"

      done | grep -Ei -v "ViewOnly|Depl" | head -n 1
    )
    echo -e "\nSelecting '$profile'\n" >&2
  fi

  echo "$profile"
}

aws-login() {
  if [[ $1 == @(-c|console) ]]; then
    shift
    console=1
  fi
  aws-sso eval -p "$(aws-sso-profile "$@")" >"$AWS_SSO_CACHE"
  source "$AWS_SSO_CACHE"
  aws-whoami
  [[ $console ]] && aws-console "$@"
}

aws-console() {
  if (($# > 0)); then
    x-www-browser "https://${AWS_REGION:-$AWS_DEFAULT_REGION}.console.aws.amazon.com/$1"
  else
    aws-sso console -p "${AWS_SSO_PROFILE:-$(aws-sso-profile "$@")}"
  fi
}
