#!/bin/bash

fzf_install_dir="$XDG_DATA_HOME/fzf"
fzf_bin_dir="$fzf_install_dir/bin"

install-fzf() {
  if [[ ! -d $fzf_install_dir ]]; then
    git clone https://github.com/junegunn/fzf.git "$fzf_install_dir"
  fi

  ( builtin cd $fzf_install_dir;
    echo "Updating $fzf_install_dir"
    git remote -v
    git clean -f -d -q
    git reset --hard origin/master
    git pull origin master
  )

  cp -av "$fzf_bin_dir/"* ~/.local/bin/

  local latest_tag=$(curl -fsSL 'https://api.github.com/repos/junegunn/fzf/releases/latest' | jq -cer '.tag_name')
  local url="https://github.com/junegunn/fzf/releases/download/$latest_tag/fzf-${latest_tag}-linux_amd64.tar.gz"
  local file="${url##*/}"
  local _TMP=$(mktemp -d)

  ( cd "$_TMP"
    echo "Fetching release $latest_tag from $url"
    wget -qc "$url" -O "$file"
    tar zxvf "$file" -C ~/.local/bin
  )

  rm -fr "$_TMP"
  fzf --version
}

if [[ $- == *i* ]]; then
  fzf_overlay_dir="${fzf_install_dir}-overlay"

  source "$fzf_install_dir/shell/completion.bash"   2> /dev/null
  source "$fzf_install_dir/shell/key-bindings.bash" 2> /dev/null

  if [[ -d $fzf_overlay_dir ]]; then
    for overlay in "$fzf_overlay_dir"/*sh; do
      source "$overlay"
    done
  fi
fi
