#!/bin/bash

function __my_git_ps1 {
  t=$(__git_ps1 | sed -r 's/^ *\(|\) *$//g')

  s=0

  t="${t//feature\//f\/}"
  t="${t//bugfix\//b\/}" 
  t="${t//release\//r\/}"
  t="${t//hotfix\//h\/}" 
  t="${t//support\//s\/}"


  gs=$(git status)

  if grep -iq "Changes not staged" <<<"$gs"; then
    printf '\001%s\002%s\001%s\002' "$red" "$t" "$reset"
    return
  fi

  if grep -iq "^Untracked files:" <<<"$gs"; then
    printf '\001%s\002%s\001%s\002' "$orange_166" "$t" "$reset"
    return
  fi

  printf '\001%s\002%s\001%s\002' "$green_36" "$t" "$reset"
}
