#!/bin/bash

function __my_git_ps1 {
  git_ps1_text=$(__git_ps1 '%s')

  if [[ -z $git_ps1_text ]] || (( ${#git_ps1_text} == 0 )); then
    printf '\001%s\002%s\001%s\002'  "$bold$grey_236" "-" "$reset"
    return
  fi
  s=0

  git_ps1_text="${git_ps1_text//feature\//f\/}"
  git_ps1_text="${git_ps1_text//bugfix\//b\/}" 
  git_ps1_text="${git_ps1_text//release\//r\/}"
  git_ps1_text="${git_ps1_text//hotfix\//h\/}" 
  git_ps1_text="${git_ps1_text//support\//s\/}"

  gs=$(git status)

  if grep -iq "Changes not staged" <<<"$gs"; then
    printf '\001%s\002%s\001%s\002' "$red" "$git_ps1_text" "$reset"
  elif grep -iq "^Untracked files:" <<<"$gs"; then
    printf '\001%s\002%s\001%s\002' "$orange_166" "$git_ps1_text" "$reset"
  else
    printf '\001%s\002%s\001%s\002' "$green_36" "$git_ps1_text" "$reset"
  fi

  if ahead=$(grep -iPo "(?:behind|ahead of) '.*?' by \d+" <<<"$gs" | grep -Po '\d+$'); then
    printf '\001%s\002%s\001%s\002'  "$bold$red_196" "+$ahead" "$reset"
    return
  fi

}
