#!/bin/bash

# SYNOPSIS
#   goss aliases

install-goss() {
  local latest_tag=$(curl -fsSL 'https://api.github.com/repos/aelsabbahy/goss/releases/latest' | jq -cer '.tag_name')
  echo "aelsabbahy/goss/releases/latest reports $latest_tag"
  goss --version | grep "$latest_tag$" || rm -fv ~/.local/bin/goss
  local url="https://github.com/aelsabbahy/goss/releases/download/$latest_tag/goss-linux-amd64"
  ( cd ~/.local/bin/
    test -x goss || wget -c "$url" -O goss
    chmod +x goss
  )
  set +xv
}
