#!/bin/bash

# SYNOPSIS
#   helm aliases

# from https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu
install-helm() {
  curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
  sudo apt-get install apt-transport-https --yes
  echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  sudo apt-get update
  sudo apt-get install helm
  helm version
  source <(helm completion bash)
}

@has-cmd helm || return

source <(helm completion bash)
