#!/bin/bash

shopt -s histappend

# append history entries to ~/.config/bash/bash_history
HISTFILE=~/.config/bash/bash_history
HISTFILESIZE="32768"
HISTSIZE="$HISTFILESIZE"
HISTTIMEFORMAT='%FT%T'$'\t'
HISTCONTROL=ignoredups
