#!/bin/bash

# SYNOPSIS
#   kubectl aliases

# from https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu
install-kubectl() {
  # Add the Cloud SDK distribution URI as a package source
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" |
    sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list

  # Import the Google Cloud Platform public key
  curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

  # Update the package list and install kubectl
  sudo apt-get update && sudo apt-get install kubectl
}

@has-cmd kubectl || return

_kubectl-mode-init() {
  if systemctl status k3s.service &>/dev/null; then
    KUBECTL_MODE=${KUBECTL_MODE:-k3s}
  fi
}

[[ -z $KUBECTL_MODE ]] && _kubectl-mode-init

if [[ $KUBECTL_MODE = 'k3s' ]]; then
  kubectl() {
    command k3s kubectl $@
  }
else
  kubectl() {
    command kubectl $@
  }
fi

source <(kubectl completion bash)

alias k='kubectl'
complete -o default -F __start_kubectl k
