#!/bin/bash

# SYNOPSIS
#   kubectl aliases

install-kubectl() {
  type -a kubectl &>/dev/null && return
  local latest=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
  curl -C - -LO https://storage.googleapis.com/kubernetes-release/release/$latest/bin/linux/amd64/kubectl
  chmod +x kubectl
  install -p kubectl ~/.local/bin/
  hash -r
  kubectl version
}

@has-cmd kubectl || return

_kubectl-mode-init() {
  if systemctl status k3s.service &>/dev/null; then
    KUBECTL_MODE=${KUBECTL_MODE:-k3s}
  fi
}

[[ -z $KUBECTL_MODE ]] && _kubectl-mode-init

if [[ $KUBECTL_MODE = 'k3s' ]]; then
  kubectl() {
    command k3s kubectl $@
  }
else
  kubectl() {
    command kubectl $@
  }
fi

source <(kubectl completion bash)

alias k='kubectl'
complete -o default -F __start_kubectl k
