#!/bin/bash

# Description

loadenv() {
  if [[ -f .env ]]; then
    set -a; source .env; set +a
  else
    echo >&2 "No .env found in $PWD"
  fi
}

# vim: syntax=sh cc=80 tw=79 ts=2 sw=2 sts=2 et sr
