#!/bin/bash

if [[ -z "$debian_chroot" && -r /etc/debian_chroot ]]; then
  debian_chroot="$(</etc/debian_chroot)"
fi

sumarker=
if [[ $EUID == 0 || $UID == 0 ]]; then
  sumarker='\$'
else
  sumarkers=(
    ℥ ℮ ⅁ ⅂ ⅃ ⅄ ☀ ☂ ★ ☆ ☊ ☌ ☍ ☓ ☘ ☡ ☥
    ☫ ☿ ♀ ♁ ♂ ♃ ♄ ♅ ♇ ♈ ♉ ♊ ♋ ♌ ♎ ♏ ♐ ♑ ♓ ⚒
    ⚓ ⚔ ⚕ ⚜ ⚡ ⚲ ⚴ ⚷ ⚸ ꞉ ヽ ヾ ￠ ＄ ￡ ￥ ￦ ȧ
    Ȧ ꜹ ꜻ ꜽ ⱥ Ⱥ ɐ Ɐ ɑ Ɑ ɒ Ɒ ℬ ʙ Ƀ ɓ ℭ ȼ Ȼ ɕ ↄ Ↄ
    ℯ ℰ Ȩ Ɇ ɛ ɤ ℱ Ꝼ Ꞡ ʛ ɣ ʄ Ⱪ ɭ ꞎ ɮ Ꞁ ʎ Ɱ Ꞥ Ȣ Ᵽ ꝑ Ꝓ ȹ Ꝗ ɋ
    Ɋ Ꞧ Ꞃ Ȿ ʃ ʅ ț Ț Ꞇ Ɥ ʮ Ʌ X Ȳ Ɏ Ȝ ℤ ℨ Ȥ
    Ɀ Ⱬ ʒ ꝥ ꝧ Ꝩ Ꜫ Ɂ β γ ℽ Γ δ Δ ϝ ζ η θ λ ξ π Π Ϟ
    Σ ς τ υ φ ϕ Φ χ ψ Ψ ω Ω ℵ ℶ ℷ ℸ あ ｧ ア ｱ ぃ
    い イ お オ か カ が ガ き キ ｷ ぎ ギ く ク ｸ ぐ
    だ ダ ち チ て テ で デ と ぬ ヌ の
    プ ペ ホ め メ ゆ わ ヰ ヺ ん ン 火 个 丫 中
  )
  sumarker="${sumarkers[ $RANDOM % ${#sumarkers[@]} ]}"
fi

case "$TERM" in
  @(screen|tmux)*)
    PS1='\[$dim\]'
    PS1+='${debian_chroot:+($debian_chroot)}'
    PS1+='\[$orange_166\]$(e=$?;echo $e;exit $e)'
    PS1+='\[$cyan\]$(e=$?;date +%T|tr -d :;exit $e)'
    PS1+='\[$grey_240\]\!'
    PS1+='\[$bold$blue_32\]\W'
    PS1+='\[$reset\]'
    PS1+='$(e=$?;__my_git_ps1;exit $e)'
    PS1+='\[$bold\]'
    PS1+=' '
    PS1+='$( [ $? -ge 1 ] && echo \[$red\]$sumarker || echo \[$blue\]$sumarker )'
    PS1+='\[$reset\]'
    PS1+=' '
    ;;
  *)
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00;37m\]:\[\033[00;34m\]\W $sumarker\[$reset\] '
;;
esac

# vi:ft=bash fenc=utf-8
