#!/bin/bash

source ~/.config/bash/rc.d/colors

if [[ -z "$debian_chroot" && -r /etc/debian_chroot ]]; then
  debian_chroot="$(</etc/debian_chroot)"
fi

sumarker=
if [[ $EUID == 0 || $UID == 0 ]]; then
  sumarker='\$'
else
  sumarkers=(
    㐃 ℥ ℮ ℺ ⅀ ⅁ ⅂ ⅃ ⅄ ☀ ☂ ★ ☆ ☊ ☌ ☍ ☓ ☘ ☡ ☥
    ☫ ☿ ♀ ♁ ♂ ♃ ♄ ♅ ♇ ♈ ♉ ♊ ♋ ♌ ♎ ♏ ♐ ♑ ♓ ⚒
    ⚓ ⚔ ⚕ ⚜ ⚡ ⚲ ⚴ ⚷ ⚸ ꞈ ꞉ ꞊ ヽ ヾ ￠ ＄ ￡ ￥ ￦ ȧ
    Ȧ ꜹ ꜻ ꜽ ⱥ Ⱥ ɐ Ɐ ɑ Ɑ ɒ Ɒ ℬ ʙ Ƀ ɓ ℭ ȼ Ȼ ɕ ↄ Ↄ
    ꜿ Ꜿ ȸ ʣ ʥ ʤ ɖ ɗ ȡ ℯ ℰ ȩ Ȩ ɇ Ɇ ⱻ ə ɛ ɘ ɚ ɜ ɝ ɞ ʚ ɤ
    ℱ ꝼ Ꝼ ʩ ꜰ ꞡ Ꞡ ɡ ɢ ɠ ʛ ɣ ɉ Ɉ ʝ ɟ ʄ ꞣ Ꞣ ⱪ Ⱪ ʞ ʪ
    ʫ ɬ ɭ ꞎ ȴ ɮ ꞁ Ꞁ ʎ ɱ Ɱ ꞥ Ꞥ ɴ ɲ Ƞ ꞑ Ꞑ ɳ ȵ o O ȫ Ȫ
    ȭ Ȭ ȯ Ȯ ȱ Ȱ ɶ ɔ ⱺ ɵ ɷ ȣ Ȣ Ᵽ ꝑ Ꝑ Ꝓ ɸ ⱷ ȹ ꝗ Ꝗ ʠ ɋ
    Ɋ ꞧ Ꞧ ꞃ Ꞃ ʀ ɍ Ɍ ɹ ɺ ɻ ⱹ ɼ ɽ Ɽ ɾ ɿ ʁ ꞩ Ꞩ ș Ș ꞅ
    Ꞅ ꜱ ʂ ȿ Ȿ ʃ ʅ ʆ ț Ț ꞇ Ꞇ ʨ ʦ ʧ ꜩ ⱦ Ⱦ ʈ ȶ ʇ ʉ Ʉ ɥ
    Ɥ ʮ ʯ ɯ ɰ ʊ ⱽ ʋ ⱱ ⱴ ʌ Ʌ ʍ X ȳ Ȳ ʏ ɏ Ɏ ȝ Ȝ ℤ ℨ ȥ Ȥ
    ʐ ʑ ɀ Ɀ ⱬ Ⱬ ʒ ʓ ꝥ Ꝥ ꝧ Ꝧ ꝩ Ꝩ ꜫ Ꜫ ʔ ɂ Ɂ ꜣ Ꜣ α
    β γ ℽ Γ δ Δ ε ϵ ϝ ζ η θ Θ ι κ λ μ ν ξ ο π ℼ Π Ϟ ρ σ
    Σ ς τ υ φ ϕ Φ χ ψ Ψ ω Ω ℵ ℶ ℷ ℸ ぁ あ ァ ｧ ア ｱ ぃ
    い ィ ｨ イ ｲ ぅ う ゥ ｩ ウ ｳ ゔ ヴ ぇ え ェ ｪ エ ｴ ぉ
    お ォ ｫ オ ｵ か ヵ カ ｶ が ガ き キ ｷ ぎ ギ く ク ｸ ぐ
    グ け ヶ ケ ｹ げ ゲ こ コ ｺ ご ゴ さ サ ｻ ざ ザ し シ ｼ
    じ ジ す ス ｽ ず ズ せ セ ｾ ぜ ゼ そ ソ ｿ ぞ ゾ た タ ﾀ
    だ ダ ち チ ﾁ ぢ ヂ っ つ ッ ｯ ツ ﾂ づ ヅ て テ ﾃ で デ
    と ト ﾄ ど ド な ナ ﾅ に ニ ﾆ ぬ ヌ ﾇ ね ネ ﾈ の ノ ﾉ
    は ハ ﾊ ば バ ぱ パ ひ ヒ ﾋ び ビ ぴ ピ ふ フ ﾌ ぶ ブ ぷ
    プ へ ヘ ﾍ べ ベ ぺ ペ ほ ホ ﾎ ぼ ボ ぽ ポ ま マ ﾏ み ミ
    ﾐ む ム ﾑ め メ ﾒ も モ ﾓ ゃ や ャ ｬ ヤ ﾔ ゅ ゆ ュ ｭ
    ユ ﾕ ょ よ ョ ｮ ヨ ﾖ ゟ ら ラ ﾗ り リ ﾘ る ル ﾙ れ レ
    ﾚ ろ ロ ろヮ ゎ わ ヮ ワ ﾜ ヷ ゐ ヰ ヸ ゑ ヱ ヹ を ヲ ｦ
    ヺ ん ン ﾝ ㆒ ㆜ ㆔ ㆖ ㆘ ㆛ ㆗ ㆚ ㆓ ㆟ ㆕ ㆞ ㆝ ㆙火 个
    丫 中 乇
  )
  sumarker="${sumarkers[ $RANDOM % ${#sumarkers[@]} ]}"
fi

case "$TERM" in
  @(screen|tmux)*)
    PS1='\[$dim\]'
    PS1+='${debian_chroot:+($debian_chroot)}'
    PS1+='\[$grey_240\]\!'
    PS1+='\[$orange_166\]$(e=$?;echo $e;exit $e)'
    PS1+='\[$cyan\]$(e=$?;date +%T|tr -d :;exit $e)'
    PS1+='\[$reverse\]'
    PS1+='\[$bold$blue_32\] \W '
    PS1+='$(e=$?;__my_git_ps1;exit $e)'
    PS1+='\[$bold\]'
    PS1+=' '
    PS1+='$( [ $? -ge 1 ] && echo \[$red\]$sumarker || echo \[$blue\]$sumarker )'
    PS1+='\[$reset\]'
    PS1+=' '
    ;;
  *)
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00;37m\]:\[\033[00;34m\]\W $sumarker\[$reset\] '
;;
esac

# vi:ft=bash fenc=utf-8
