#!/bin/bash

# emit pwd(1) and also copy $PWD to the clipboard
function pwd() {
  builtin pwd
  echo "$PWD" |
    tee ~/.cache/dir-selected |
    if [[ -n $DISPLAY ]]; then
      command -v xclip && xclip -in
    fi &>/dev/null
}
