#!/bin/bash

cargo-install() {
  if [[ -r ~/.cargo/env ]]; then
    echo >&2 "Sourcing ~/.cargo/env"
    source ~/.cargo/env
  else
    sudo apt-get install pkg-config libssl-dev
    # https://github.com/rust-lang/rustup/issues/297#issuecomment-444818896
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    cargo-init
  fi

  ( set -xv
  rustup update
  cargo install cargo-update
  cargo install-update cargo-update
  )
}
