#!/bin/bash

# set_cursor_colour

# tmux
if [[ ${TMUX-} ]]; then
  # cursor shape is a short underscore
  # see .vim/rc6.d/colours.vim for codes
  # solid block
  printf '\033Ptmux;\033\033[2 q\033\\'
  # cursor color
  printf '\033Ptmux;\033\033]12;darkcyan\007\033\\'
else
  # rxvt
  printf '\033]12;red\007'
fi
