#!/bin/bash

export TF_PLUGIN_CACHE_DIR="$HOME/.cache/terraform.d/plugin-cache"

[[ ! -d "$TF_PLUGIN_CACHE_DIR" ]] && mkdir -p "$TF_PLUGIN_CACHE_DIR"

export TF_CLI_CONFIG_FILE="$TF_PLUGIN_CACHE_DIR/terraform.rc"
