#!/bin/bash

ulimit -Sc 128000       # core dump file size
ulimit -Sd 512000       # data segment size
ulimit -Se 2            # max. nice value
ulimit -Sf 512000       # max. files created
ulimit -Sm 512000       # max. resident set size
ulimit -Sn 2048         # open files
ulimit -Ss 128000       # max. stack size
ulimit -St 45           # soft max. CPU time in seconds
ulimit -Ht 60           # hard max. CPU time in seconds
ulimit -Su 512          # soft max. user processes
ulimit -Hu 768          # hard max. user processes
ulimit -Sv 512000       # max. virtual memory

