---

jira_api_base_url: https://onetakeda.atlassian.net
jira_api_username: shalom.bhooshi@takeda.com
jira_api_token: ATATT3xFfGF0sxrSiboqxkMNEdqaXWq88quQN-I6oJiEVmrpMJ2QxJLHOK5JWofebhzNptrb9YZqLtT1cdPo4G_PMVTR5qEUcNp8QQFajSwNyW0zi0gL99uxmzzIIPf9JX1scZdNxhFWQsidee31nYrl-SQICk7iDnAMgPQxX4QYhtgGZ7foBv4=0855FC29
