#!/bin/bash

type -P rsync &> /dev/null || {
  echo "rsync is not installed or is not in '$PATH'" >&2
}

abs_path () {
  target=$(readlink -f "$1")
  echo "$target"
}

abs_dir () {
  target=$(abs_path "$1")
  [[ -d $target ]] || {
    echo "'abs_dir($1) != directory' failed."
  }
}

make_link() {
  local src="$1"
  local dst="$2"
  local opts="$3"

  if [[ -f "$src" ]]; then 
    rsync -PavclpEAXH "$opts" \
      --link-dest=$(dirname "$(abs_path "$src")")/ "$src" "$dst"

  else
    rsync -PavclpEAXH "$opts" \
      --link-dest=$(abs_path "$src")/ "$src"/ "$dst"/
  fi

}

cmd="$1"
opts="${opts}"

if    [[ $cmd = stash ]]; then     # import
  for file; do
    make_link "$file" "$target"
  done

elif  [[ $cmd = export ]]; then  # export
  for file; do
    make_link "$file" "$target"
  done

fi
