#!/bin/bash

set -x

( set -exv
  git submodule init
  git submodule update --init --recursive
  git submodule -q foreach git pull -q origin master
  git submodule status
)

find .[!.]*/ */ -name "INIT" -type f -exec {} \;

find .[!.]* \
  \( -name ".git" -type d -o -name "*.sw?" -o -name "*~" \) -prune \
  -o -type f -exec ./dotfile_stash export {} +
