#!/bin/bash 

set -eu

if [[ ! -d .vim ]]; then
  { echo "No $PWD/.vim directory found." 
    echo "  Are you in the root of you dotfiles directory?"
  } >&2
  exit 3
fi

pkgs_to_install=()
type -P ack-grep &>/dev/null || pkgs_to_install+=( 'ack-grep' )
type -P ctags    &>/dev/null || pkgs_to_install+=( 'exuberant-ctags' )
type -P git      &>/dev/null || pkgs_to_install+=( 'git' )
type -P hg       &>/dev/null || pkgs_to_install+=( 'mercurial' )
type -P jq       &>/dev/null || pkgs_to_install+=( 'jq' )
type -P par      &>/dev/null || pkgs_to_install+=( 'par' )
type -P sudo     &>/dev/null || pkgs_to_install+=( 'sudo' )
type -P ssh-askpass     &>/dev/null || pkgs_to_install+=( 'ssh-askpass' )

if (( ${#pkgs_to_install[@]} >= 1 )); then
  echo "Installing pre-requisites ... ${pkgs_to_install[@]}"
  (set -xv; sudo aptitude install ${pkgs_to_install[@]})
fi

mkdir -p .vim/bundle/

ln -svf .vim/vimrc  .vimrc
ln -svf .vim/gvimrc .gvimrc

( set +e -xv
  cd .vim/

  git submodule add -f https://github.com/AndrewRadev/switch.vim.git            bundle/switch
  git submodule add -f https://github.com/avakhov/vim-yaml.git                  bundle/yaml
  git submodule add -f https://github.com/christoomey/vim-tmux-navigator.git    bundle/tmux-navigator
  git submodule add -f https://github.com/coderifous/textobj-word-column.vim.git bundle/textobj-word-column
  git submodule add -f https://github.com/easymotion/vim-easymotion.git         bundle/easymotion
  git submodule add -f https://github.com/ekalinin/Dockerfile.vim.git           bundle/dockerfile
  git submodule add -f https://github.com/endel/vim-github-colorscheme.git      bundle/github-colorscheme
  git submodule add -f https://github.com/ervandew/supertab.git                 bundle/supertab
  git submodule add -f https://github.com/gabrielelana/vim-markdown.git         bundle/markdown
  git submodule add -f https://github.com/Glench/Vim-Jinja2-Syntax.git          bundle/jinja2-syntax
  git submodule add -f https://github.com/glidenote/memolist.vim.git            bundle/memolist
  git submodule add -f https://github.com/godlygeek/tabular.git                 bundle/tabular
  git submodule add -f https://github.com/hsitz/VimOrganizer.git                bundle/VimOrganizer
  git submodule add -f https://github.com/jceb/vim-orgmode.git                  bundle/orgmode
  git submodule add -f https://github.com/jgdavey/tslime.vim.git                bundle/tslime
  git submodule add -f https://github.com/kana/vim-arpeggio.git                 bundle/arpeggio
  git submodule add -f https://github.com/kien/ctrlp.vim.git                    bundle/ctrlp
  git submodule add -f https://github.com/kshenoy/vim-sol.git                   bundle/sol
  git submodule add -f https://github.com/majutsushi/tagbar.git                 bundle/tagbar
  git submodule add -f https://github.com/mattn/calendar-vim.git                bundle/calendar-vim
  git submodule add -f https://github.com/mileszs/ack.vim.git                   bundle/ack
  git submodule add -f https://github.com/msanders/snipmate.vim.git             bundle/snipmate
  git submodule add -f https://github.com/PProvost/vim-ps1.git                  bundle/ps1
  git submodule add -f https://github.com/pydave/vim-perforce.git               bundle/perforce
  git submodule add -f https://github.com/shalomb/vimcse.git                    vimcse
  git submodule add -f https://github.com/shinokada/dragvisuals.vim.git         bundle/dragvisuals
  git submodule add -f https://github.com/takac/vim-hardtime.git                bundle/hardtime
  git submodule add -f https://github.com/tmux-plugins/vim-tmux.git             bundle/tmux
  git submodule add -f https://github.com/tomasr/molokai.git                    bundle/molokai
  git submodule add -f https://github.com/tpope/vim-abolish.git                 bundle/abolish
  git submodule add -f https://github.com/tpope/vim-commentary.git              bundle/commentary
  git submodule add -f https://github.com/tpope/vim-fugitive.git                bundle/fugitive
  git submodule add -f https://github.com/tpope/vim-pathogen.git                bundle/pathogen
  git submodule add -f https://github.com/tpope/vim-ragtag.git                  bundle/ragtag
  git submodule add -f https://github.com/tpope/vim-repeat.git                  bundle/repeat
  git submodule add -f https://github.com/tpope/vim-sleuth.git                  bundle/sleuth
  git submodule add -f https://github.com/tpope/vim-speeddating.git             bundle/speeddating
  git submodule add -f https://github.com/tpope/vim-surround.git                bundle/surround
  git submodule add -f https://github.com/tpope/vim-unimpaired.git              bundle/unimpaired
  git submodule add -f https://github.com/vimoutliner/vimoutliner.git           bundle/vimoutliner
  git submodule add -f https://github.com/vim-scripts/css.vim--Streppone.git    bundle/streppone--css
  git submodule add -f https://github.com/vim-scripts/DrawIt.git                bundle/drawit
  git submodule add -f https://github.com/vim-scripts/genutils.git              bundle/genutils
  git submodule add -f https://github.com/vim-scripts/Gundo.git                 bundle/gundo
  git submodule add -f https://github.com/vim-scripts/iptables.git              bundle/iptables
  git submodule add -f https://github.com/vim-scripts/matchit.zip.git           bundle/matchit
  git submodule add -f https://github.com/vim-scripts/netrw.vim.git             bundle/netrw
  git submodule add -f https://github.com/vim-scripts/perl-mauke.vim.git        bundle/mauke-perl
  git submodule add -f https://github.com/vim-scripts/perlprove.vim.git         bundle/perlprove
  git submodule add -f https://github.com/vim-scripts/sharp-Indent.git          bundle/sharp-indent
  git submodule add -f https://github.com/vim-scripts/sharp-Syntax.git          bundle/sharp-indent
  git submodule add -f https://github.com/vim-scripts/sharp-Syntax--Rim.git     bundle/fsharp-plugin
  git submodule add -f https://github.com/vim-scripts/ShowMarks.git             bundle/ShowMarks
  git submodule add -f https://github.com/vim-scripts/taglist.vim.git           bundle/taglist
  git submodule add -f https://github.com/vim-scripts/underlinetag.git          bundle/underlinetag
  git submodule add -f https://github.com/vim-scripts/vimwiki.git               bundle/vimwiki
  git submodule add -f https://github.com/vim-scripts/vis.git                   bundle/vis
  git submodule add -f https://github.com/vim-scripts/VST.git                   bundle/vst     # Vim reStructured Text
  git submodule add -f https://github.com/zirrostig/vim-schlepp.git             bundle/schlepp

  git submodule init
  git submodule update --init --recursive
  git submodule -q foreach git pull -q origin master
  git submodule status
)

exit $?;

COMMITTING NOTES (Requires Authentication)
  cd ~/.vim
  git add .
  git commit -m "Commit on $(date); "
  git remote add origin git@github.com:shalomb/.vim.git
  git push origin master

REFERENCES
  "Synchronizing plugins with git submodules and pathogen" http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen/
