#!/bin/bash 

if [[ ! -d .vim ]]; then
  echo "No .vim directory found." >&2
  exit 3
fi

ln -svf .vim/vimrc  .vimrc
ln -svf .vim/gvimrc .gvimrc

(
  git submodule add -f https://github.com/christoomey/vim-tmux-navigator.git    .vim/bundle/vim-tmux-navigator
  git submodule add -f https://github.com/godlygeek/tabular.git                 .vim/bundle/tabular
  git submodule add -f https://github.com/hsitz/VimOrganizer.git                .vim/bundle/VimOrganizer
  git submodule add -f https://github.com/jceb/vim-orgmode.git                  .vim/bundle/vim-orgmode
  git submodule add -f https://github.com/kana/vim-arpeggio.git                 .vim/bundle/arpeggio
  git submodule add -f https://github.com/kien/ctrlp.vim.git                    .vim/bundle/ctrlp
  git submodule add -f https://github.com/majutsushi/tagbar.git                 .vim/bundle/tagbar
  git submodule add -f https://github.com/mileszs/ack.vim.git                   .vim/bundle/ack
  git submodule add -f https://github.com/msanders/snipmate.vim.git             .vim/bundle/snipmate
  git submodule add -f https://github.com/PProvost/vim-ps1.git                  .vim/bundle/vim-ps1
  git submodule add -f https://github.com/pydave/vim-perforce.git               .vim/bundle/vim-perforce
  git submodule add -f https://github.com/shalomb/vimcse.git                    .vim/vimcse
  git submodule add -f https://github.com/tomasr/molokai.git                    .vim/bundle/molokai
  git submodule add -f https://github.com/tpope/vim-pathogen.git                .vim/bundle/pathogen
  git submodule add -f https://github.com/tpope/vim-repeat.git                  .vim/bundle/repeat
  git submodule add -f https://github.com/tpope/vim-speeddating.git             .vim/bundle/vim-speeddating
  git submodule add -f https://github.com/tpope/vim-surround.git                .vim/bundle/surround
  git submodule add -f https://github.com/tpope/vim-unimpaired.git              .vim/bundle/unimpaired
  git submodule add -f https://github.com/tsaleh/vim-tmux.git                   .vim/bundle/vim-tmux
  git submodule add -f https://github.com/vimoutliner/vimoutliner.git           .vim/bundle/vimoutliner
  git submodule add -f https://github.com/vim-scripts/css.vim--Streppone.git    .vim/bundle/streppone--css.vim
  git submodule add -f https://github.com/vim-scripts/DrawIt.git                .vim/bundle/drawit
  git submodule add -f https://github.com/vim-scripts/genutils.git              .vim/bundle/genutils 
  git submodule add -f https://github.com/vim-scripts/Gundo.git                 .vim/bundle/gundo
  git submodule add -f https://github.com/vim-scripts/iptables.git              .vim/bundle/iptables
  git submodule add -f https://github.com/vim-scripts/Markdown.git              .vim/bundle/markdown
  git submodule add -f https://github.com/vim-scripts/matchit.zip.git           .vim/bundle/matchit
  git submodule add -f https://github.com/vim-scripts/netrw.vim.git             .vim/bundle/netrw
  git submodule add -f https://github.com/vim-scripts/perl-mauke.vim.git        .vim/bundle/mauke-perl.vim
  git submodule add -f https://github.com/vim-scripts/perlprove.vim.git         .vim/bundle/perlprove.vim
  git submodule add -f https://github.com/vim-scripts/sharp-Indent.git          .vim/bundle/sharp-indent
  git submodule add -f https://github.com/vim-scripts/sharp-Syntax.git          .vim/bundle/sharp-indent
  git submodule add -f https://github.com/vim-scripts/sharp-Syntax--Rim.git     .vim/bundle/fsharp-plugin
  git submodule add -f https://github.com/vim-scripts/ShowMarks.git             .vim/bundle/ShowMarks
  git submodule add -f https://github.com/vim-scripts/SuperTab-continued..git   .vim/bundle/supertab-continued 
  git submodule add -f https://github.com/vim-scripts/taglist.vim.git           .vim/bundle/taglist
  git submodule add -f https://github.com/vim-scripts/underlinetag.git          .vim/bundle/underlinetag
  git submodule add -f https://github.com/vim-scripts/vimwiki.git               .vim/bundle/vimwiki
  git submodule add -f https://github.com/vim-scripts/VST.git                   .vim/bundle/vst     # Vim reStructured Text

  git submodule init
  git submodule update
  git submodule -q foreach git pull -q origin master
)

exit $?;

COMMITTING NOTES (Requires Authentication)
  cd ~/.vim
  git add .
  git commit -m "Commit on $(date); "
  git remote add origin git@github.com:shalomb/.vim.git
  git push origin master

REFERENCES
  "Synchronizing plugins with git submodules and pathogen" http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen/
