#!/bin/bash

set -eu

if [[ ! -d .vim ]]; then
  { echo "No $PWD/.vim directory found."
    echo "  Are you in the root of you dotfiles directory?"
  } >&2
  exit 3
fi

pkgs_to_install=()
type -P ack      &>/dev/null || pkgs_to_install+=( 'ack' )
type -P ctags    &>/dev/null || pkgs_to_install+=( 'exuberant-ctags' )
type -P git      &>/dev/null || pkgs_to_install+=( 'git' )
type -P jq       &>/dev/null || pkgs_to_install+=( 'jq' )
type -P par      &>/dev/null || pkgs_to_install+=( 'par' )
type -P sudo     &>/dev/null || pkgs_to_install+=( 'sudo' )
type -P ssh-askpass     &>/dev/null || pkgs_to_install+=( 'ssh-askpass' )

if (( ${#pkgs_to_install[@]} >= 1 )); then
  echo "Installing pre-requisites ... ${pkgs_to_install[@]}"
  (set -xv; sudo aptitude install ${pkgs_to_install[@]})
fi

mkdir -p .vim/bundle/

ln -svf .vim/vimrc  .vimrc
ln -svf .vim/gvimrc .gvimrc

( set +e -xv
  cd .vim/

  git submodule add -f https://github.com/airblade/vim-gitgutter.git            bundle/gitgutter
  git submodule add -f https://github.com/AndrewRadev/switch.vim.git            bundle/switch
  git submodule add -f https://github.com/avakhov/vim-yaml.git                  bundle/yaml
  git submodule add -f https://github.com/christoomey/vim-tmux-navigator.git    bundle/tmux-navigator
  git submodule add -f https://github.com/easymotion/vim-easymotion.git         bundle/easymotion
  git submodule add -f https://github.com/ekalinin/Dockerfile.vim.git           bundle/dockerfile
  git submodule add -f https://github.com/garbas/vim-snipmate.git               bundle/snipmate
  git submodule add -f https://github.com/Glench/Vim-Jinja2-Syntax.git          bundle/jinja2-syntax
  git submodule add -f https://github.com/godlygeek/tabular.git                 bundle/tabular
  git submodule add -f https://github.com/hashivim/vim-terraform.git            bundle/terraform
  git submodule add -f https://github.com/honza/vim-snippets.git                bundle/snipmate-snippets
  git submodule add -f https://github.com/idbrii/textobj-word-column.vim.git    bundle/textobj-word-column
  git submodule add -f https://github.com/jgdavey/tslime.vim.git                bundle/tslime
  git submodule add -f https://github.com/junegunn/fzf.git                      bundle/fzf-core
  git submodule add -f https://github.com/junegunn/fzf.vim.git                  bundle/fzf
  git submodule add -f https://github.com/junegunn/vim-peekaboo.git             bundle/peekaboo
  git submodule add -f https://github.com/MarcWeber/vim-addon-mw-utils.git      bundle/mw-utils
  git submodule add -f https://github.com/mileszs/ack.vim.git                   bundle/ack
  git submodule add -f https://github.com/shalomb/ansible-snippets.git          bundle/ansible-snippets
  git submodule add -f https://github.com/shinokada/dragvisuals.vim.git         bundle/dragvisuals
  git submodule add -f https://github.com/takac/vim-hardtime.git                bundle/hardtime
  git submodule add -f https://github.com/tamlok/vim-markdown.git               bundle/markdown
  git submodule add -f https://github.com/terryma/vim-multiple-cursors.git      bundle/multiple-cursors
  git submodule add -f https://github.com/thanthese/Tortoise-Typing.git         bundle/tortoise-typing
  git submodule add -f https://github.com/tmux-plugins/vim-tmux.git             bundle/tmux
  git submodule add -f https://github.com/tomasr/molokai.git                    bundle/molokai
  git submodule add -f https://github.com/tommcdo/vim-exchange.git              bundle/exchange
  git submodule add -f https://github.com/tomtom/tlib_vim.git                   bundle/tlib
  git submodule add -f https://github.com/tpope/vim-abolish.git                 bundle/abolish
  git submodule add -f https://github.com/tpope/vim-commentary.git              bundle/commentary
  git submodule add -f https://github.com/tpope/vim-fugitive.git                bundle/fugitive
  git submodule add -f https://github.com/tpope/vim-pathogen.git                bundle/pathogen
  git submodule add -f https://github.com/tpope/vim-ragtag.git                  bundle/ragtag
  git submodule add -f https://github.com/tpope/vim-repeat.git                  bundle/repeat
  git submodule add -f https://github.com/tpope/vim-sleuth.git                  bundle/sleuth
  git submodule add -f https://github.com/tpope/vim-speeddating.git             bundle/speeddating
  git submodule add -f https://github.com/tpope/vim-surround.git                bundle/surround
  git submodule add -f https://github.com/tpope/vim-unimpaired.git              bundle/unimpaired
  git submodule add -f https://github.com/vim-scripts/genutils.git              bundle/genutils
  git submodule add -f https://github.com/vim-scripts/Gundo.git                 bundle/gundo
  git submodule add -f https://github.com/vim-scripts/matchit.zip.git           bundle/matchit
  git submodule add -f https://github.com/vim-scripts/netrw.vim.git             bundle/netrw
  git submodule add -f https://github.com/vim-scripts/ShowMarks.git             bundle/ShowMarks
  git submodule add -f https://github.com/vim-scripts/taglist.vim.git           bundle/taglist
  git submodule add -f https://github.com/vim-scripts/underlinetag.git          bundle/underlinetag
  git submodule add -f https://github.com/vim-scripts/vis.git                   bundle/vis  # Extended VISual commands
  git submodule add -f https://github.com/zirrostig/vim-schlepp.git             bundle/schlepp

  git submodule update --init --recursive
  git submodule sync
  git submodule -q foreach '
    echo "Synchronizing ${PWD##*dotfiles/}";
    git fetch -q --all --prune;
    git checkout -q master;
    git pull -q;
  '
  git submodule status | sed -r 's/[()]//g' | column -t
)

exit $?;

COMMITTING NOTES (Requires Authentication)
  cd ~/.vim
  git add .
  git commit -m "Commit on $(date); "
  git remote add origin git@github.com:shalomb/.vim.git
  git push origin master

REFERENCES
  "Synchronizing plugins with git submodules and pathogen" http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen/
