#!/bin/bash 

set -x

ln -sv .vim/vimrc  .vimrc
ln -sv .vim/gvimrc .gvimrc

(
  git submodule add -f https://github.com/godlygeek/tabular.git               .vim/bundle/tabular
  git submodule add -f https://github.com/hsitz/VimOrganizer.git              .vim/bundle/VimOrganizer
  git submodule add -f https://github.com/kana/vim-arpeggio.git               .vim/bundle/arpeggio
  git submodule add -f https://github.com/msanders/snipmate.vim.git           .vim/bundle/snipmate
  git submodule add -f https://github.com/shalomb/vimcse.git                  .vim/vimcse
  git submodule add -f https://github.com/sjbach/lusty.git                    .vim/bundle/lusty
  git submodule add -f https://github.com/tpope/vim-pathogen.git              .vim/bundle/pathogen
  git submodule add -f https://github.com/tpope/vim-repeat.git                .vim/bundle/repeat
  git submodule add -f https://github.com/tpope/vim-surround.git              .vim/bundle/surround
  git submodule add -f https://github.com/tpope/vim-unimpaired.git            .vim/bundle/unimpaired
  git submodule add -f https://github.com/tsaleh/vim-tmux.git                 .vim/bundle/vim-tmux
  git submodule add -f https://github.com/vimoutliner/vimoutliner.git         .vim/bundle/vimoutliner
  git submodule add -f https://github.com/vim-scripts/css.vim--Streppone.git  .vim/bundle/streppone--css.vim
  git submodule add -f https://github.com/vim-scripts/DrawIt.git              .vim/bundle/drawit
  git submodule add -f https://github.com/vim-scripts/Gundo.git               .vim/bundle/gundo
  git submodule add -f https://github.com/vim-scripts/iptables.git            .vim/bundle/iptables
  git submodule add -f https://github.com/vim-scripts/ManPageView.git         .vim/bundle/manpageview
  git submodule add -f https://github.com/vim-scripts/Markdown.git            .vim/bundle/markdown
  git submodule add -f https://github.com/vim-scripts/matchit.zip.git         .vim/bundle/matchit
  git submodule add -f https://github.com/vim-scripts/netrw.vim.git           .vim/bundle/netrw
  git submodule add -f https://github.com/pydave/vim-perforce.git             .vim/bundle/vim-perforce
  git submodule add -f https://github.com/vim-scripts/perl-mauke.vim.git      .vim/bundle/mauke-perl.vim
  git submodule add -f https://github.com/vim-scripts/perlprove.vim.git       .vim/bundle/perlprove.vim
  git submodule add -f https://github.com/vim-scripts/sharp-Indent.git        .vim/bundle/sharp-indent
  git submodule add -f https://github.com/vim-scripts/sharp-Syntax.git        .vim/bundle/sharp-indent
  git submodule add -f https://github.com/vim-scripts/sharp-Syntax--Rim.git   .vim/bundle/fsharp-plugin
  git submodule add -f https://github.com/vim-scripts/ShowMarks.git           .vim/bundle/ShowMarks
  git submodule add -f https://github.com/vim-scripts/SuperTab-continued..git .vim/bundle/supertab-continued 
  git submodule add -f https://github.com/vim-scripts/taglist.vim.git         .vim/bundle/taglist
  git submodule add -f https://github.com/vim-scripts/underlinetag.git        .vim/bundle/underlinetag
  git submodule add -f https://github.com/vim-scripts/vimwiki.git             .vim/bundle/vimwiki
  git submodule add -f https://github.com/vim-scripts/Windows-PowerShell-File-Type-Plugin.git  .vim/bundle/posh-ftplugin
  git submodule add -f https://github.com/vim-scripts/Windows-PowerShell-indent-enhanced.git   .vim/bundle/posh-indent
  git submodule add -f https://github.com/vim-scripts/Windows-PowerShell-Syntax-File.git       .vim/bundle/posh-syntax
  git submodule add -f https://github.com/wincent/Command-T.git                .vim/bundle/command-t

  git submodule init
  git submodule update
)

exit $?;

COMMITTING NOTES (Requires Authentication)
  cd ~/.vim
  git add .
  git commit -m "Commit on $(date); "
  git remote add origin git@github.com:shalomb/.vim.git
  git push origin master

REFERENCES
  "Synchronizing plugins with git submodules and pathogen" http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen/
