#!/bin/bash

# Vim plugins/prerequisites manager

# REFERENCES
# [Synchronizing plugins with git submodules and pathogen]
# (http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen/)

set -eu -o pipefail

vim_base=".config/vim"

if [[ ! -d $vim_base ]]; then
  { echo "No $vim_base directory found."
    echo "  Are you in the root of the dotfiles directory?"
  } >&2
  exit 3
fi

pkgs_to_install=()
type -P ack      &>/dev/null || pkgs_to_install+=( 'ack' )
type -P ctags    &>/dev/null || pkgs_to_install+=( 'exuberant-ctags' )
type -P git      &>/dev/null || pkgs_to_install+=( 'git' )
type -P jq       &>/dev/null || pkgs_to_install+=( 'jq' )
type -P par      &>/dev/null || pkgs_to_install+=( 'par' )
type -P sudo     &>/dev/null || pkgs_to_install+=( 'sudo' )

if (( ${#pkgs_to_install[@]} >= 1 )); then
  echo "Installing pre-requisites ... ${pkgs_to_install[@]}"
  (set -xv; sudo apt install -yqq ${pkgs_to_install[@]})
fi

mkdir -p "$vim_base/bundle/"

ln -svf "$vim_base/vimrc"      .vimrc
ln -svf "$vim_base/vimrc.gvim" .gvimrc

exit

# TODO
# here lie dragons - this part is no longer maintained as neovim rules now

install-vimplugin() {
  local github_repo="$1"
  local github_repo_normalized="${github_repo//\//--}"
  github_repo="https://github.com/$github_repo.git"
  bundle_dir="bundle/$github_repo_normalized"
  tweak_file="rc0.d/$github_repo_normalized.vim"
  # Install submodule
  ( set -eu
    git submodule add -f "$github_repo" "$bundle_dir"
    touch "$tweak_file"
    git add "$tweak_file"
  )
}

( set +e
  cd "$vim_base"

  # for some reason pathogen has to be installed as ~/.vim/bundle/pathogen
  git submodule add -f https://github.com/tpope/vim-pathogen.git bundle/pathogen

  install-vimplugin airblade/vim-gitgutter
  install-vimplugin AndrewRadev/switch.vim
  install-vimplugin avakhov/vim-yaml
  install-vimplugin chrisbra/unicode.vim
  install-vimplugin christoomey/vim-tmux-navigator
  install-vimplugin davidhalter/jedi-vim
  install-vimplugin dbeniamine/cheat.sh-vim
  install-vimplugin dense-analysis/ale
  install-vimplugin easymotion/vim-easymotion
  install-vimplugin editorconfig/editorconfig-vim
  install-vimplugin ekalinin/Dockerfile.vim
  install-vimplugin fatih/vim-go
  install-vimplugin garbas/vim-snipmate
  install-vimplugin gioele/vim-autoswap
  install-vimplugin Glench/Vim-Jinja2-Syntax
  install-vimplugin godlygeek/tabular
  install-vimplugin hashivim/vim-terraform
  install-vimplugin haya14busa/incsearch-easymotion.vim   bundle/incsearch-easymotion
  install-vimplugin haya14busa/incsearch-fuzzy.vim
  install-vimplugin haya14busa/incsearch.vim              bundle/incsearch
  install-vimplugin haya14busa/vim-asterisk
  install-vimplugin haya14busa/vim-operator-flashy
  install-vimplugin honza/vim-snippets
  install-vimplugin idbrii/textobj-word-column.vim
  install-vimplugin instant-markdown/vim-instant-markdown
  install-vimplugin jeetsukumaran/vim-markology
  install-vimplugin jeetsukumaran/vim-pythonsense
  install-vimplugin jgdavey/tslime.vim
  install-vimplugin jiangmiao/auto-pairs
  install-vimplugin junegunn/fzf
  install-vimplugin junegunn/fzf.vim
  install-vimplugin junegunn/goyo.vim
  install-vimplugin junegunn/rainbow_parentheses.vim
  install-vimplugin junegunn/vim-peekaboo
  install-vimplugin kana/vim-operator-user
  install-vimplugin kana/vim-textobj-fold
  install-vimplugin kana/vim-textobj-function
  install-vimplugin kana/vim-textobj-indent
  install-vimplugin kana/vim-textobj-line
  install-vimplugin kana/vim-textobj-user
  install-vimplugin kana/vim-textobj-user
  install-vimplugin majutsushi/tagbar
  install-vimplugin MarcWeber/vim-addon-mw-utils
  install-vimplugin mileszs/ack.vim
  install-vimplugin preservim/vim-markdown
  install-vimplugin rhysd/clever-f.vim
  install-vimplugin romainl/vim-cool
  install-vimplugin rstacruz/vim-closer
  install-vimplugin shalomb/ansible-snippets
  install-vimplugin takac/vim-hardtime
  install-vimplugin tamlok/vim-markdown
  install-vimplugin terryma/vim-multiple-cursors
  install-vimplugin thanthese/Tortoise-Typing
  install-vimplugin tmux-plugins/vim-tmux
  install-vimplugin tmux-plugins/vim-tmux-focus-events
  install-vimplugin tomasr/molokai
  install-vimplugin tommcdo/vim-exchange
  install-vimplugin tomtom/tlib_vim
  install-vimplugin tpope/vim-abolish
  install-vimplugin tpope/vim-commentary
  install-vimplugin tpope/vim-endwise
  install-vimplugin tpope/vim-fugitive
  install-vimplugin tpope/vim-pathogen
  install-vimplugin tpope/vim-ragtag
  install-vimplugin tpope/vim-repeat
  install-vimplugin tpope/vim-sleuth
  install-vimplugin tpope/vim-speeddating
  install-vimplugin tpope/vim-surround
  install-vimplugin tpope/vim-unimpaired
  install-vimplugin tpope/vim-vinegar
  install-vimplugin tyjak/vim-redact-pass
  install-vimplugin vim-scripts/genutils
  install-vimplugin vim-scripts/Gundo
  install-vimplugin vim-scripts/matchit.zip
  install-vimplugin vim-scripts/netrw.vim
  install-vimplugin vim-scripts/underlinetag
  install-vimplugin vim-scripts/vis
  install-vimplugin vimwiki/vimwiki
  install-vimplugin wellle/targets.vim
  install-vimplugin wellle/visual-split.vim
  install-vimplugin xolox/vim-easytags
  install-vimplugin xolox/vim-misc
  install-vimplugin zirrostig/vim-schlepp

)

exit $?
