""" Pathogen  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
runtime bundle/pathogen/autoload/pathogen.vim
filetype off

call pathogen#infect('bundle/{}')
Helptags


"""" Environmental Variables """""""""""""""""""""""""""""""""""""""""""""""""

let $MYVIMRUNTIME=resolve(split(&runtimepath,',')[0])
set shell=/bin/bash

"""" Options """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" set nocompatible            "

" set term=$TERM            " term is $TERM
set more                    " page on extended output

set backupdir=/tmp          " put backups in /tmp
set backupdir-=.            " ...and not in cwd

set hidden                  " hide, don't close, undisplayed buffers
set history=8192            " lines of command history to keep

set laststatus=2            " always show status line

set shortmess=fimnrwxatIWO  " Get rid of most messages
set cmdheight=2             " Set command height to 2 to avoid netrw pains
set report=1                " Always report changes
set ruler                   " display cursor position
set showcmd                 " show command-in-progress
set showmode                " mode shown in lower left
set title                   " set the term's window title

set noerrorbells            " no bell on error messages
set visualbell              " use a visual bell instead
set t_vb=                   " but don't set a control code - so no flashing screen

set foldcolumn=1            " no fold column
set foldlevelstart=0        " start with all folds closed
set modeline                " enable modelines contra debian, TODO: secure this

set nostartofline           " try and keep cursor from moving to BOL
set formatoptions=r         " r - re-insert comment leader on newline
set terse                   " add 's' to 'shortmess'
set timeout                 " allow keys to timeout
set wildmenu                " enable menu of completions
set wildmode=longest,list,full " longest common string, then each full match
set wildcharm=<C-Z>         " keybinding that charms the wild complete
set completeopt=longest,menuone,preview

set mouse=                  " mouse is available in all modes
if has('mouse')
  set mousemodel=popup_setpos
  set mousehide               " hide the mouse when busy
endif

set backspace=2             " correct backspace to return to previous lines

set incsearch               " searches are displayed on-the-fly
set hlsearch                " searches are highlighted
set ignorecase              " ignore case when searching
set smartcase               " except when searching upper case patterns
set wrapscan                " wrap around EOF on searches

set tabstop=2               " 2 characters
set softtabstop=2           " tabs are always 'tabstop' positions
set shiftwidth=2            " 2 characters
set expandtab               " expand tabs to spaces
set smarttab                " smart tab size
set shiftround              " indent rounded to shiftwidth

set number                  " turn on line numbers
set relativenumber          " turn on relative line numbers
set numberwidth=3           " with 3 digits by default

set wrap                    " wrap long lines
set wrapmargin=2            " clear 2 at the RHS
set linebreak               " soft-break at non-word characters
set nolist                  " soft-wrap seems to play up if list is set
set splitright              " create new vsplits to the right of current window
set splitbelow              " create new splits to the bottom of current window

set scrolloff=2             " always keep 2 lines in view at top/bottom margin
set sidescroll=2            " ss: only scroll horizontally little by little
set sidescrolloff=2         " siso: places a couple columns between the current
                            "   column and the screen edge
set autoread                " autoload file when modified externally
set hidden                  " mark modified buffers hidden automatically

filetype plugin indent on   " try and guess what type of file
filetype detect
syntax enable               " enable syntax highlighting
syntax on                   " start highlighting
set fileformat=unix         " no CR-LF, just plain newlines

set autoindent              " try and be smart about indenting
set cindent                 " done better
set copyindent              " make autoindent use the same characters to indent
set cinkeys-=0#             " disable commenting moving us to the BOL
set indentkeys-=0#          " disable commenting moving us to the BOL
set nojoinspaces

set showmatch               " show matching braces, parantheses, brackets, etc
set matchpairs+=<:>         " show and % jump matching brackets
set matchpairs+=(:)
set matchpairs+={:}
set matchpairs+=[:]
set matchpairs+==:;         " variable assignments, etc
set matchtime=5             " Show match sec;
set showcmd                 " show input command??;

set timeoutlen=1000         " timeout (ms) waited for key sequence to complete

set pastetoggle=<F11>

set iskeyword+=:

set path=.,~,..,
let &path = &path . "," . $OLDPWD

let g:pwd            = getcwd()
let g:invocation_pwd = getcwd()

"""" Set Viminfo """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set viminfo='10,\"100,:256,%,n~/.local/viminfo

"""" abbrevs """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"""" Keybindings """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let mapleader = ","

"""" Source RC File """"""""""""""""""""""""""""""""""""""""""""""""""""""""""
function! SourceRcFiles(path)
  for file in split(glob(a:path . '/**.vim'),'\n')
    execute 'source ' . file
  endfor
endfunction

function! Reload(path)
  for d in split(glob(a:path),'\n')
    call SourceRcFiles(d)
  endfor
endfunction

call Reload('~/.vim/rc*d')

