use-agent
pinentry-mode loopback

# [GnuPG - ArchWiki](https://wiki.archlinux.org/index.php/GnuPG#gpg-agent)
personal-digest-preferences SHA512
cert-digest-algo            SHA512
default-preference-list     SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
personal-cipher-preferences TWOFISH CAMELLIA256 AES 3DES

utf8-strings
# display-charset utf-8       # bypass all translation and assume that the OS uses native UTF-8 encoding
