#!/bin/bash

if [[ ! -d .tmux ]]; then
  { echo "No $PWD/.tmux directory found." 
    echo "  Are you in the root of you dotfiles directory?"
  } >&2
  exit 3
fi

pkgs_to_install=()
type -P sudo     &>/dev/null || pkgs_to_install+=( 'sudo' )
type -P tmux     &>/dev/null || pkgs_to_install+=( 'tmux' )

if (( ${#pkgs_to_install[@]} >= 1 )); then
  echo "Installing pre-requisites ... ${pkgs_to_install[@]}"
  (set -xv; sudo aptitude install ${pkgs_to_install[@]})
fi

mkdir -p .tmux/plugins
cd .tmux/

if (cd "$PWD/.git" &>/dev/null;
    git rev-parse --is-inside-git-dir | grep -iq true); then
  git pull
else
  git init
fi


( set +e -xv
  git submodule add -f https://github.com/tmux-plugins/tpm                 plugins/tpm
  # git submodule add -f https://github.com/tmux-plugins/tmux-copycat.git    plugins/tmux-copycat
  # git submodule add -f https://github.com/tmux-plugins/tmux-yank.git       plugins/tmux-yank
  # git submodule add -f https://github.com/tmux-plugins/tmux-continuum.git  plugins/tmux-continuum

  git submodule init
  git submodule update --init --recursive
  git submodule -q foreach git pull -q origin master
  git submodule status
)

