#!/bin/bash

# shared functions

# Check if running in interactive shell
@is-interactive() {
  [[ ${-//[!i]/} ]]
}

# Check if a command exists
has-cmd() {
    command -v "$1" >/dev/null 2>&1
}

# Compatibility alias for old scripts
@has-cmd() {
    has-cmd "$@"
}

warn() {
  echo >&2 "$BOLD$RED$@$RESET"
}

die() {
  warn "$@"
  return 1  ## NOTE: not exit to allow for proper use
             #       in interactive shells where this
             #       would otherwise exit the shell
}

function set-title() {
  local text="$1"
  [[ -z $text ]] &&
    text='\033]0;${debian_chroot}${USER}@${screen_session:-$HOSTNAME}:$$: ${PWD/$HOME/~}\007'
  echo -ne "$text"
}

function chpwd() {
  # called everytime working directory is changed
  CDPATH="$PWD:$OLDPWD:..:~:/media:/mnt:$HOME/projects"
}

function bell-alert() {
  printf '\a'

  if [[ $# && $TMUX ]]; then
    tmux list-clients -F "#{client_name}" |
      xargs -I{} tmux display-message -c {} "$@"
  fi
}

# Check if function is defined
function defined() {
  declare -F "$1" >/dev/null 2>&1
}

function call-if-defined() {
  defined "$1" && "$1"
}

