#!/bin/bash

set -xv

outfile="${2:-${0##*/}}-$(date --rfc-3339=ns | tr ' ' 'T').gif";
tmpfile=$(mktemp "${outfile##*/}.XXXXXXXX.avi")

ffcast -s % ffmpeg -y -f x11grab -show_region 1 -framerate 15 \
    -video_size %s -i %D+%c -codec:v huffyuv                  \
    -vf crop="iw-mod(iw\\,2):ih-mod(ih\\,2)" "$tmpfile"      \
  && convert -set delay 10 -layers Optimize "$tmpfile" "$outfile"

rm -f "$tmpfile" || true

