#!/bin/bash

test -t 0 || exec > "$TMP"/osd_msg.log 2>&1

pidfile="$TMP"/osd_msg.pid
duration="${osd_msg_duration:-"3"}"

if [[ -f $pidfile ]]; then
  read -r timestamp duration pid < "$pidfile"
  echo "[$timestamp] [$duration] [$pid]";
  current_timestamp="$(date +%s)"
  if (( (timestamp+duration) > current_timestamp )); then
    kill "$pid"
  fi
fi

# dzen2 -p 2 -bg green -fg black -y -20 -fn "-b&h-lucida-bold-r-normal-sans-14-240-75-75-p-152-iso8859-1"  <<<"$@"

echo "$@" | \
  osd_cat -l 2 -p bottom -o 60 \
  -d "$duration" -A center -c green \
  -s 1 \
  -f "-*-*-bold-*-normal-*-20-240-*-*-*-*-*-*" \
  & pid="$!"

echo "$(date +%s) $duration $pid" > "$pidfile"

