#!/bin/bash

[[ $@ ]] && echo "ARGS: $@"
p4_words=()

set -a 

[[ -f $P4CONFIG ]] && source $P4CONFIG
[[ -f ~/.config/p4settings ]] && source ~/.config/p4settings
[[ -f ~/.p4settings ]] && source ~/.p4settings

P4DIFFUNICODE="${P4DIFFUNICODE:-/usr/bin/gvimdiff}"
P4DIFF="${P4DIFF:-/usr/bin/gvimdiff}"
P4EDITOR="${P4EDITOR:-/usr/bin/gvim}"
P4MERGE="${P4MERGE:-"$P4DIFF"}"
P4MERGEUNICODE="${P4MERGEUNICODE:-"$P4MERGE"}"

P4USER="${P4USER:-shalomb}"
P4HOST="${P4HOST:-kratos.theos.local}"
P4CLIENT="${P4CLIENT:-shalomb_kratos}"
P4PORT="${P4PORT:-camsrc.eng.citrite.net:2555}"

function usage {
cat <<EOF
  p4_init [help|reset [all]]
EOF
}

if   [[ "$@" = *help* ]]; then
  usage; return
elif [[ "$@" = *reset* ]]; then
  if [[ "$@" = *all* ]]; then
    p4_words=(P4DIFFUNICODE P4DIFF P4EDITOR P4MERGE P4MERGEUNICODE)
  fi
  p4_words+=(P4USER P4HOST P4CLIENT P4PORT)

  for v in "${p4_words[@]}"; do
    read -p "$(printf 'set %-8s [%s] : ' "$v" "${!v}")" val
    if [[ $val ]] && [[ $val != ${!v} ]]; then
      printf "  %s='%s'\n" "$v" "$val"
      IFS= read -r "$v" <<<"$val"
    fi
  done
fi

set +a

if p4 login -s &> /dev/null || p4 login -p; then
  p4 login -s
  p4 tickets | while IFS=" )(" read -r h u t; do
    echo "$u@${h,,} $t"
  done | column -t

  p4 set | sort | while IFS="=" read -r k v; do 
    printf '  %-18s %s\n' "$k" "$v"
  done

  p4 info | while IFS=":" read -r k v; do 
    printf '  %-18s%s\n' "$k" "$v"
  done
fi


