#!/bin/bash

set -eu

projects_list="$XDG_CACHE_HOME/projects.list"

while getopts 'u' opt; do
  case "$opt" in
    u) update=1
      ;;
  esac
done
shift $((OPTIND -1))

projects_find() {
find ~ -iname ".git" |
  sed -r 's@/.git@@' |
  while read d; do
    ( cd "$d" && git remote -v | awk '/fetch/{ print $2 }'
    ) 2>/dev/null | sed -r 's@^@'"$d"' @';
  done | column -t
}

if [[ -n ${update-} ]] || [[ ! -e $projects_list ]]; then
  projects_find > "$projects_list"
fi

cat "$projects_list"
