#!/bin/bash

set -eu
shopt -s nullglob

if [[ -z ${vpn_name-} ]]; then
  vpn_name="${1:-${0##*/}}"
fi

config_file=~/.config/shuttle/vpns/$vpn_name 

if [[ -e $config_file ]]; then
  exec "$config_file"
else
  echo "Missing config file ($config_file) for sshuttle VPN '$vpn_name'"
  echo ''
  echo "  Available VPN configurations"
  for i in ~/.config/shuttle/vpns/*; do
    echo "    ${i##*/}"
  done
fi
