#!/bin/bash

# vi: filetype=sh:sw=2:tw=2:et:ai

# NAME
#   tips - invoke tip files on demand

# SYNOPSIS
#   tips [word|word..]]
#   tips / shell_command args

# DESCRIPTION

shopt -s extglob nocaseglob nocasematch

if [[ -e ~/.config/tips/config ]]; then
  source ~/.config/tips/config
fi

tipsdir="${tipsdir:-~/tips}"

if [[ ! -d "$tipsdir" ]]; then
  echo "No such directory '$tipsdir', $!"
  exit 2
fi

function list_tips() {
  local pattern="$1"
  find * \( -name ".[!.]?*" \) \
    -prune -o -iregex ".*$pattern.*" -print0 | sort -z
}

oldpwd="$PWD"
cd "$tipsdir"
if (( $# == 0 )) || [[ $1 = @(-l|--ls|--list) ]]; then
  list_tips | perl -lpe 'BEGIN{$/="\0"}' | column | less
  exit $?
elif [[ $1 = "/" ]]; then
  shift;
  cmd="$1"; shift;
  ( set -x; "$cmd" "$@"; set +x; ) 2>&1 | less
  exit $?;
fi

search_terms=()

for glob in "$@"; do

  if [[ ${glob:0:1} = "/" ]]; then
    search_term="$glob"
    search_term="${search_term##/}"
    search_term="${search_term%%/}"
    search_terms+=( "$search_term" )
  else
    while read -d $'' file; do
      files+=( "$file" )
    done < <( list_tips "$glob" )
  fi
done

if (( ${#files[@]} == 0 )); then
  if (( $# == 0 )); then
    files=( . )
  else
    files=( "$@" )
  fi
fi

files=( "${files[@]//\/\///}" )
files=( "${files[@]//\*/}"    )

for f in "${files[@]}"; do
  dir="${f%%/*}";
  if [[ $dir != $f ]] && [[ ! -d $dir ]]; then
    mkdir -vp "$dir"
  fi
done

echo "$0 [$PWD]: Editing the following .. "
printf "  %s\n" ${files[@]}

search_term="${search_terms[@]}"
vim -c "silent! /${search_term// /\\|}/e" -c 'norm ggnzv' "${files[@]}"

cd "$oldpwd"
