#!/bin/bash

# vi: filetype=sh:sw=2:tw=2:et:ai:foldmethod=marker:foldmarker={{{,}}}

# NAME
#   tips - invoke tip files on demand
#
# SYNOPSIS
#   tips [word|word..]]
#   tips / shell_command args
#
# DESCRIPTION

shopt -s extglob nocaseglob nocasematch 

tipsdir=~/Desktop/tips

if [[ ! -d "$tipsdir" ]]; then
  echo "No such directory '$tipsdir', $!"
  exit 2
fi

oldpwd="$PWD"
cd "$tipsdir"
if (( $# == 0 )) || [[ $1 = @(-l|--list) ]]; then
  find * .[!.]* \( -name ".hg" -type d -o -iname "*sw?" \) \
    -prune -o -type f -printf '%p\n' \
    | column | less
  exit 1;
elif [[ $1 = "/" ]]; then
  shift;
  cmd="$1"; shift;
  ( set -x; "$cmd" "$@"; set +x; ) 2>&1 | less
  exit $?;
fi

for glob in "$@"; do
  while read -d $'' file; do
    files+=( "$file" ) 
  done < <( find * \( -name ".[!.]?*" -prune \) \
    -o -ipath "*$glob*" -print0 | sort -z )
done

if (( ${#files[@]} == 0 )); then
  if (( $# == 0 )); then
    files=( . )
  else
    files=( "$@" )
  fi
fi

files=( "${files[@]//\/\///}" ) 
files=( "${files[@]//\*/}"    )

for f in "${files[@]}"; do
  dir="${f%%/*}";
  if [[ $dir != $f ]] && [[ ! -d $dir ]]; then
    mkdir -vp "$dir"
  fi
done

( IFS=$', '; echo "$PWD: Editing ${files[*]}" );

editor "${files[@]}"  # assuming a sane editor!!

cd "$oldpwd"
