#!/bin/bash

set -eu

if ! type -P tmux &> /dev/null; then
  echo "tmux not installed (in \$PATH)?" >&2
  exit 2
fi

sessions=()
while read -r session; do 
  sessions+=( "$session" )
done < <( tmux ls )

if (( ${#sessions[@]} == 0 )); then
  printf 'No sessions, launch new one? [y/N] '; read n
  if [[ -z $n || $n = [nN] ]]; then 
    exit 1; 
  else
    exec tmux
  fi
fi

for i in "${!sessions[@]}"; do
  echo "$i. ${sessions[i]}"
done
printf 'Which one? '; read n

set -vx
if [[ -z $n ]]; then exit 1; fi

if [[ $n = *[!0-9]* ]] || (( n < 0 || n > ${#sessions[@]}-1 )); then
  echo "No such session. $n";
  exit 2;
fi

exec tmux attach -t "${sessions[n]//:*/:}"
