#!/bin/bash

TMP=$( mktemp -d --tmpdir="${TMP:-/tmp}" wfica.XXXXXXXX )
cd "$TMP"

exec >> >(tee -a wfica.log) 2>&1

set -xv

export ICAROOT=/opt/Citrix/ICAClient 
ica_file="$1"

# Some defaults
#  ScreenPercent=100 # TODO, not currently supported
#  DesiredHRES=1280
#  DesiredVRES=1024

# Source our own wfica conf file if it exists
#  We hope DesiredVRES and DesiredHRES are set within it
[[ -r $XDG_DATA_HOME/wfica/wfica.conf ]] && \
  source "$XDG_DATA_HOME/wfica/wfica.conf"


if [[ -z $DesiredVRES || -z $DesiredHRES ]]; then
  # If DesiredHRES and DesiredVRES are not set (from within the conf file),
  # get the largest current resolution of this $DISPLAY and use those
  # values instead.
  res=( $(xrandr | \
          awk '
            BEGIN{ max=0 } 
            /^\ +[0-9]+x[0-9]+\ .*\*/{ 
              split($1, res, "x"); 
              if(res[1] > max) max=res[1]" "res[2] 
            } 
            END{ print max }' \
        ) );

  DesiredHRES="${res[0]}"
  DesiredVRES="${res[1]}"
fi

mv -v "$ica_file" .
ica_file="$PWD/${ica_file##*/}"

(
  set +xv
  echo "# ---- ICA file : $ica_file -------------------"
  base64_string="${ica_file##*/}"
  base64 -d <<< "${base64_string%%.ica}"
  echo ''
  echo "# ---- Env ------------------------------------"
  env
  echo ''
  echo "# ---- ICA file ($ica_file) original below ----"
  cat -et "$ica_file"
  echo '# ---------------------------------------------'
  echo ''
);

# Make our substitutions to the ica file
sed -i.orig \
  -e 's@DesiredHRES=.*@DesiredHRES='"$DesiredHRES"'@' \
  -e 's@DesiredVRES=.*@DesiredVRES='"$DesiredVRES"'@' \
  "$ica_file"

(
  set +xv
  echo ''
  echo "# ---- ICA file ($ica_file) diff below --------"
  diff "$ica_file"{.orig,}
  echo '# ---------------------------------------------'
  echo ''
);

# Pass on to wfica
exec -a wfica "$ICAROOT/wfica" \
  -file "$ica_file" \
  -geometry "$DesiredHRES"x"$DesiredVRES"+0+0 \
  -log

#  -fileparam "$HOME/" # File not accessible by remote programs??
