#!/bin/bash

# NAME
#   wminmark - mark and summon windows.

set -x
test -t 0 || exec > ~/.tmp/winmark.log 2>&1

if [[ ! -d ~/.tmp/winmarks ]]; then
  mkdir -p ~/.tmp/winmarks || \
    { echo "Error creating the winmarks directory, $!"; exit 2; };
fi

cd ~/.tmp/winmarks

pwd

action="${1:-"mark"}"
mark="${2:-"'"}"
duration="${osd_msg_duration:-"10"}"

if   [[ $action = mark ]]; then
  curwin="$(printf "0x%08x" "$(xprop -root _NET_ACTIVE_WINDOW | grep -Eio "0x[[:xdigit:]]+")")";
  touch "$curwin";
  ln -svf "$curwin" "$mark";

  duration="${osd_msg_duration:-"3"}"
  wmctrl -lx | \
    perl -lane '
        $F[0]=~/'"$curwin"'/ and 
          print join " ", 
            qw["'"$mark"'"], "\t",
            "\"$F[2]\"", "\t",
            q/"/, (join " ", @F[4..$#F]), q/"/
      ' | \
    tee "$curwin" | \
    osd_msg "$( < /dev/stdin )"

elif [[ $action = summon ]]; then
  winid="$(readlink "$mark")";
  wmctrl -i -a "${winid##*/}";

elif [[ $action = list ]]; then
  set +v +x
  for i in ?; do
    printf "%s %s %s %s\n" "$i" $(< $i)
  done 

fi
