#!/bin/bash

set -eu

source "$XDG_CONFIG_HOME/winmark/defaults"

cd "$winmarks_dir"

wid=$( printf "0x%08x" "$1" )

wmclass=$( wmctrl -lx | awk -v id="$wid" '$1 == id{ print $3 }' )
wminstance="${wmclass%.*}"
wmclass="${wmclass##*.}"

if [[ $wmclass = @(Firefox)* ]]; then
  mark="${wmclass:0:1}"
elif [[ $wminstance = libreoffice-* ]]; then
  mark="${wminstance##*-}"
  mark="${mark:0:1}"
else
  mark="${wminstance:0:1}"
fi

mark=$(tr 'A-Z' 'a-z' <<<"$mark")

echo "Class:    $wmclass"
echo "Instance: $wminstance"
echo "Mark:     $mark"

mark_file=$(readlink -f "$mark" || true)

if [[ ${mark_file##*/} != $wid ]] || [[ ! -e $mark_file ]]; then
  rm -f "$mark_file"
  winmark mark "$mark" "$wid"
fi

if [[ $wminstance == qterm ]]; then
  [[ -e q ]] || winmark mark '@' "$wid"

elif [[ $wminstance == spotify ]]; then
  [[ -e p ]] || winmark mark 'p' "$wid"

fi

