#!/bin/bash

set -eu

sudo apt-get -yyq --no-install-recommends --no-install-suggests install nodejs npm

sudo npm install \
  @devcontainers/cli \
  @pnp/cli-microsoft365 \
  @vscode/codicons \
  neovim \
  pyright \
  tree-sitter \
  tree-sitter-cli
