#!/bin/bash

set -eu

sudo apt-get -yyq --no-install-recommends --no-install-suggests install nodejs npm

sudo npm install \
  @anthropic-ai/claude-code \
  @devcontainers/cli \
  @github/copilot \
  @google/gemini-cli \
  @pnp/cli-microsoft365 \
  bash-language-server \
  markdownlint-cli2 \
  mcp-hub \
  neovim \
  tree-sitter \
  vsce \
  write-good
