# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 3.2
brew "bash-completion"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Password manager
brew "pass"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# High-performance system programming language
brew "swift"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Application launcher and productivity software
cask "alfred"
# E-books management software
cask "calibre"
# Online diagram software
cask "drawio"
# Excalidraw client
cask "excalidrawz"
# Web browser
cask "firefox"
# Web browser
cask "firefox@developer-edition"
# Screenshot software
cask "flameshot"
# Screen colour temperature controller
cask "flux"
cask "font-symbols-only-nerd-font"
# Web browser
cask "google-chrome"
# End-to-end encryption software
cask "keybase"
# Clipboard manager
cask "maccy"
# File system integration
cask "macfuse"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Instant messaging application focusing on security
cask "signal"
# Music streaming service
cask "spotify"
# Open-source code editor
cask "visual-studio-code"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Video communication and virtual meeting platform
cask "zoom"
# Indoor cycling game
cask "zwift"
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
