#!/bin/bash

for key; do
  # gpg --keyserver http://keyserver.ubuntu.com --recv-key "$key";
  # gpg --keyserver http://subkeys.pgp.net --recv-key "$key";

  echo
  echo Processing key: $key
  echo

  gpg --list-key "$key" ||
    (set -xv; gpg --keyserver hkps://keyserver.ubuntu.com --recv-key "$key";)

  gpg --fingerprint "$key"

  file="/etc/apt/trusted.gpg.d/$key.gpg"
  gpg --armor --export  "$key" |
    sudo gpg --no-default-keyring --keyring gnupg-ring:"$file" --import

  (set -xv; sudo chown _apt "$file";)

  echo
done


