#!/bin/bash

 #######################################################################
#   ~/.config/bash/profile: executed by bash(1) for login shells.       #
#     Installed at ~/.bash_profile for legacy reasons.                  #
#                                                                       #
#   See /usr/share/doc/bash/examples/startup-files for examples;        #
#     these files are located in the bash-doc package.                  #
 #######################################################################

# If not running interactively, don't do anything, just return
[[ ${-//[!i]/} ]] || return 0

# the default umask is set in /etc/login.defs
umask 022

if [[ $TERM == 'linux' ]]; then
  setterm -blength 0
fi

if [[ -r ~/.config/bash/bashrc ]]; then
  source ~/.config/bash/bashrc
fi

if [[ ${TTY:-$(tty)} == /dev/tty1 ]]; then
  unset TMOUT
  tmout 5 "exec startx > $TMP/startx.log 2>&1"
  TMOUT=120
  clear
fi

export PATH="$HOME/.cargo/bin:$PATH"
