#!/bin/bash

set -eu -o pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

cd "$SCRIPT_DIR"

pip3 install --break-system-packages --upgrade --user pip

pip3 install --break-system-packages --upgrade --user $(sed -r 's/\ +/==/' requirements.txt)
