#!/bin/bash -i

fail=0
for cmd in \
  fzf \
  xflux \
; do
  echo >&2 "Checking $cmd .."
  if ! type -P "$cmd" &>/dev/null; then
    echo >&2 "$cmd requires manual installation."
    (( ${GUI:-0} == 1 )) && fail=1
  fi
done
if (( fail == 1 )); then
  exit 126
fi
