#!/bin/sh

 ##############################################################################
#   ~/.profile: executed by the command interpreter for login shells           #
#   (including bash when invoked as a --login shell).                          #
#                                                                              #
#   For non-interactive shells, this file is not read by bash(1),              #
#   if ~/.bash_profile or ~/.bash_login exists.                                #
#                                                                              #
#   See /usr/share/doc/bash/examples/startup-files for examples.               #
#   the files are located in the bash-doc package.                             #
#                                                                              #
#   Avoid bashisms at all costs!! This file is to be sourced by any POSIX      #
#   complaint shell (dash, ksh, zsh, etc), so portable scripting here is key.  #
#                                                                              #
#   No checks to test whether $0 is being run interactively should be made as  #
#   ?DM and .xinitrc/.xsession spawn the DM non-interactively (with regards    #
#   to us).                                                                    #
 ##############################################################################

PATH="$HOME/.local/bin:$HOME/.bin:$PATH"
PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin"
PATH="$PATH:/usr/local/bin:/usr/bin/:/bin/"
PATH="$PATH:/opt/bin:/usr/lib/pm-utils/bin/";
export PATH;

# The default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
umask 022

# Environment Variables
BROWSER="$(/usr/bin/which x-www-browser)";      export BROWSER;
EDITOR="${EDITOR:-"$(/usr/bin/which vi)"}";     export EDITOR;
VISUAL="$EDITOR";                              export VISUAL;
XEDITOR="${XEDITOR:-"$(/usr/bin/which gvim)"}"; export XEDITOR;

BZIP2="-9v";                              export BZIP2;

HOSTNAME="${HOSTNAME:-"$(cat /etc/hostname)"}";
HOSTNAME="${HOSTNAME:-"$(hostname -s)"}";  export HOSTNAME;
HOST="${HOST:-"$HOSTNAME"}";              export HOST;

USER="${USER:-$(id -un)}"

# # Redirect $TMP to ~/.tmp
: ${TMP=/tmp/$USER}
                       export TMP
  TEMP="$TMP";         export   TEMP;
TMPDIR="$TMP";         export TMPDIR;

mkdir -p "$TMP"
chown "$USER:$USER" "$TMP/"
chmod 1770 "$TMP/"

for file in ~/.config/profile.d/*.sh; do
  . "$file"
done

# Shell Specifics
# We now go on to setup the env. for the interactive command shell.

# If we're not running interactively, return.
test -t 0 || return

GREP_COLOR="0;36";                        export GREP_COLOR;
GREP_COLORS="${GREP_COLOR:-"1;36"}";      export GREP_COLORS;

INPUTRC=~/.inputrc;                       export INPUTRC;

LESSCHARSET='utf-8';                      export LESSCHARSET;
LESSHISTFILE="$XDG_CACHE_HOME/lesshst";   export LESSHISTFILE;
LESSHISTSIZE="512";                       export LESSHISTSIZE;
LESSKEY="$XDG_CONFIG_HOME/less/lesskey";  export LESSKEY;
LESS=' -CiMNR';                           export LESS;
type lesspipe >/dev/null 2>&1 && eval "$(lesspipe)" >/dev/null

# colourise manpages
# Begin blink
export LESS_TERMCAP_mb=$'\E[01;31m';      export LESS_TERMCAP_mb;
# begin bold
export LESS_TERMCAP_md=$'\E[01;37m';      export LESS_TERMCAP_md;
# end mode
export LESS_TERMCAP_me=$'\E[0m';          export LESS_TERMCAP_me;
# begin standout mode
export LESS_TERMCAP_so=$'\E[01;44;33m';   export LESS_TERMCAP_so;
# end standout-mode
export LESS_TERMCAP_se=$'\E[0m';          export LESS_TERMCAP_se;
# begin underline
export LESS_TERMCAP_ue=$'\E[0m';          export LESS_TERMCAP_ue;
# end underline
export LESS_TERMCAP_us=$'\E[01;32m';      export LESS_TERMCAP_us;

PAGER="${PAGER:-less}";                   export PAGER;
MANPAGER="${PAGER:-"less"}";              export MANPAGER;
MANPATH="$MANPATH:/usr/share/man/:/usr/local/share/man/:/var/cache/man/";
                                          export MANPATH
