#!/bin/sh

# SYNOPSIS
#   workspacerc - workspace init file for x sessions

wksplog="$TMP/workspacerc-`date +%s`.log"

launch() {
  cmd="$1"; shift;
  if ! killall -0 "$cmd"; then
    if type "$cmd"; then
      echo "launching '$cmd' '$@'" >> "$wksplog"
      "$cmd" "$@" &
    fi
  fi
}

{

  test -d ~/.config/fonts || {
    mkdir -p ~/.config/fonts;
    chmod 755 ~/.config/fonts;
    mkfontdir ~/.config/fonts;
  } &                 # set-up user fonts dir

  test -r ~/.config/Xdefaults  && xrdb -merge ~/.config/Xdefaults
  test -r ~/.config/Xresources && xrdb -merge ~/.config/Xresources

  if ! kill -0 "$SSH_AGENT_PID"; then
    eval `ssh-agent -s`;
  fi

  wpset &
  # xbindkeys
  # fetchmail

  # nice -n 5   idesk &

  # nice -n 0   urxvtd -q -f -o && qterm &

  for file in \
    ~/.config/xmodmap \
    ~/.config/xmodmap.d/* \
    ~/.config/xmodmap.`hostname -s`.d/* \
    ; do
      test -e "$file" && xmodmap "$file"
  done

  pgrep -f mark_last_window || mark_last_window &

  unclutter  -idle 5 &
  autocutsel --fork &
  copyq &
  laptop-detect && numlockx off &

  launch gnome-session &
  launch gnome-settings-daemon &
  launch gnome-power-manager &
  # launch gnome-keyring-daemon &
  # launch gnome-screensaver &
  launch xscreensaver &

  launch xflux -l 48.1439 -g 17.1097 &
  # setxkbmap -option ctrl:nocaps &

  launch firefox &>/dev/null
  launch evolution &>/dev/null
  launch slack
  launch qterm

  xrandr --dpi 96

  sleep 10 && ~/.config/xsetrc

} >> "$wksplog" 2>&1 &

