#!/bin/sh

# SYNOPSIS
#   workspacerc - workspace init file for x sessions
#   also see xinitrc

[ -n "${DEBUG-}" ] && set -xv

set -eu

script="${0##*/}"
session=${1:-workspace}

. ~/.profile

logdir="$TMP/log"; mkdir -p "$logdir"
logfile="$logdir/$script.log"
exec > "$logfile" 2>&1

log() {
  echo >&2 "$(date +%FT%T.%N) $script '$*' $$ $PPID : $*"
}

launch() {
  cmd="$1"; shift;
  if ! killall -0 "$cmd"; then
    if type "$cmd"; then
      { log "launching '$cmd' '$*'"
        "$cmd" "$@"
      } > "$logdir/$cmd.log" 2>&1 &
    fi
  fi
}

# NOTE
# Also see .xinitrc for daemons started early before the desktop environment
{
  log "Starting session '$session'"
  launch wpset
  pgrep -f mark_last_window ||
    launch mark_last_window

  launch unclutter  -idle 5
  launch autocutsel
  launch copyq
  laptop-detect &&
    launch numlockx off

  nice -n 0 urxvtd -q -f -o
  launch qterm
  # xrandr --dpi 96

  launch xflux -l 48.1439 -g 17.1097
  launch firefox
  launch evolution
  launch spotify
  launch slack
  launch run_keybase -g

  . ~/.config/xsetrc
  timeout=$(xset q | grep 'Screen Saver' -A 2 | awk '/timeout/{ print $2}')
  launch xidlehook --socket /tmp/xidlehook.sock --timer "$timeout" screen-lock screen-unlock
  launch autorandr --change
  launch i3-layout-manager -a
}
