#!/bin/sh

# SYNOPSIS
#   xinitrc - setup the xsession before the workspace is setup
#   also see workspacerc

[ -n "${DEBUG-}" ] && set -xv

set -eu

script="${0##*/}"
session=${1:-i3}

test -r ~/.profile && . ~/.profile

logfile="$TMP/$script.log"
exec > "$logfile" 2>&1

log() {
  echo >&2 "$(date +%FT%T.%N) $script '$*' $$ $PPID : $*"
}

start_xsession() {

  log "Starting session '$session'"

  if ! test -d ~/.config/fonts; then
    mkdir -p ~/.config/fonts;
    # set-up user fonts dir
    mkfontdir ~/.config/fonts &
  fi

  test -r ~/.config/Xdefaults  && xrdb -merge ~/.config/Xdefaults
  test -r ~/.config/Xresources && xrdb -merge ~/.config/Xresources

  for file in \
    ~/.config/xmodmap \
    ~/.config/xmodmap.d/* \
    ~/.config/xmodmap."$(hostname -s)".d/* \
    ; do
      test -e "$file" && xmodmap "$file"
  done

  systemctl --user import-environment DISPLAY
  dbus-update-activation-environment --systemd DISPLAY

  eval "$(gpg-agent --daemon --disable-scdaemon)"

  if ! kill -0 "${SSH_AGENT_PID-}"; then
    unset SSH_AGENT_PID SSH_AUTH_SOCK
    eval "$(ssh-agent -s)";
  fi

  dbus-launch start-pulseaudio-x11 &

  exec dbus-launch --exit-with-session i3
}

start_xsession
