#!/bin/sh

# SYNOPSIS
#  xsetrc

xset +fp ~/.config/fonts   # add ~/.config/fonts to the font path
xset fp rehash      # rehash the font path

xset s on           # screensaver
xset s blank        # screensaver blank
xset s 180          # after 3*60 seconds, value used by xidlehook
xset s 300          # after 3*60 seconds, value used by xidlehook

xset +dpms          # enable DPMS (Energy Star) features.
xset dpms 120 210 300  # timeouts for standby, suspend, off
xset dpms 300 320 330  # timeouts for standby, suspend, off

# override some settings that gnome-settings-daemon might set
xset b off          # Turn the bell off
xset -b             # Disable bell/speaker completely
xset r rate 175 40  # Set the keyboard repeat-rate:

# keyboard layout
setxkbmap -option ctrl:nocaps
