#!/bin/sh

# SYNOPSIS
#  xsetrc

xset +fp ~/.config/fonts   # add ~/.config/fonts to the font path
xset fp rehash      # rehash the font path

xset s on           # screensaver
xset s blank        # screensaver blank
xset s 300          # after 5*60 seconds

xset +dpms          # enable DPMS (Energy Star) features.
xset dpms 420 480 600  # timeouts for standby, suspend, off


# override some settings that gnome-settings-daemon might set
xset b on           # Turn the bell on
xset -b             # Disable bell/speaker completely
xset r rate 175 40  # Set the keyboard repeat-rate:
