#!/bin/bash

# tflint :/
curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

function go-install() {
  ( set -xv
    go install -v "$@"
  );
  echo
}

go-install github.com/cli/cli/v2/cmd/gh@latest
go-install github.com/ankitpokhrel/jira-cli/cmd/jira@latest
go-install github.com/antonmedv/fx@latest
go-install github.com/aquasecurity/tfsec/cmd/tfsec@latest
go-install github.com/canthefason/go-watcher/cmd/watcher@latest
go-install github.com/fiatjaf/jiq/cmd/jiq@latest
go-install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
go-install github.com/go-delve/delve/cmd/dlv@latest
go-install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go-install github.com/google/yamlfmt/cmd/yamlfmt@latest
go-install github.com/jesseduffield/lazygit@latest
go-install github.com/mrtazz/checkmake/cmd/checkmake@latest
go-install github.com/muesli/duf@latest
go-install github.com/nektos/act@latest
go-install github.com/spf13/cobra-cli@latest
go-install github.com/stern/stern@latest
# aws-sso: Install from main branch (v2.0.0+ required for 'login' command)
# NOTE: @latest installs v1.17.0 which lacks the 'login' command
# v2.x releases have module path misconfiguration, so use @main instead
go-install github.com/synfinatic/aws-sso-cli/cmd/aws-sso@main
go-install github.com/terraform-docs/terraform-docs@latest
go-install github.com/warrensbox/terraform-switcher@latest
go-install golang.org/x/lint/golint@latest
go-install github.com/shalomb/gum@latest
go-install github.com/shalomb/ob-cli/cmd/ob-cli@latest

# High priority development tools
go-install golang.org/x/tools/cmd/goimports@latest
go-install github.com/goreleaser/goreleaser@latest
go-install github.com/securego/gosec/v2/cmd/gosec@latest
go-install gotest.tools/gotestsum@latest
go-install github.com/onsi/ginkgo/v2/ginkgo@latest
go-install github.com/cucumber/godog/cmd/godog@latest

# Medium priority development/infra tools
go-install github.com/wagoodman/dive@latest
go-install github.com/charmbracelet/glow@latest
go-install github.com/hashicorp/hcledit@latest
go-install github.com/client9/misspell/cmd/misspell@latest
go-install golang.org/x/tools/cmd/stringer@latest

# Personal project tools
go-install github.com/shalomb/td@latest
go-install github.com/shalomb/sidecar@latest
go-install github.com/shalomb/springfield@latest
go-install github.com/shalomb/ogspy@latest
go-install github.com/shalomb/jqp@latest
