#!/bin/bash

set -xv

# tflint :/
curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

go install -v github.com/ankitpokhrel/jira-cli/cmd/jira@latest
go install -v github.com/antonmedv/fx@latest
go install -v github.com/aquasecurity/tfsec/cmd/tfsec@latest
go install -v github.com/canthefason/go-watcher/cmd/watcher@latest
go install -v github.com/fiatjaf/jiq/cmd/jiq@latest
go install -v github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go install -v github.com/google/yamlfmt/cmd/yamlfmt@latest
go install -v github.com/mrtazz/checkmake/cmd/checkmake@latest
go install -v github.com/muesli/duf@latest
go install -v github.com/synfinatic/aws-sso-cli/cmd/aws-sso@latest
go install -v github.com/terraform-docs/terraform-docs@v0.16.0
go install -v golang.org/x/lint/golint@latest
