#!/bin/bash

set -eu -o pipefail

set -xv

BINDIR="$HOME/.local/bin/"

# TPM
git submodule add -f https://github.com/tmux-plugins/tpm .config/tmux/plugins/tpm

git submodule add -f https://github.com/shalomb/octo     .config/submodules/octo
( cd .config/submodules/octo
  ln -svf  "$PWD"/{v,bin/*} "$BINDIR"
)

git submodule add -f https://github.com/shalomb/fetch-me .config/submodules/fetch-me
( cd .config/submodules/fetch-me
  ln -svf  "$PWD"/fetch-me "$BINDIR"
)

git submodule add -f https://github.com/wbthomason/packer.nvim .local/share/nvim/site/pack/packer/start/packer.nvim
