#!/bin/bash

set -eu -o pipefail

set -xv

BINDIR="$HOME/.local/bin/"

register_submodule() {
  local repo="$1"
  local dir="$2"

  if [[ ! -d "$dir" ]]; then
    git submodule add -f "$repo" "$dir"
  fi
}

declare -A submodules=(
  [.config/tmux/plugins/tpm]="https://github.com/tmux-plugins/tpm"
)

for dir in "${!submodules[@]}"; do
  register_submodule "${submodules[$dir]}" "$dir"
done

register_submodule https://github.com/shalomb/octo .config/submodules/octo
( cd .config/submodules/octo
  ln -svf  "$PWD"/{v,bin/*} "$BINDIR"
)

register_submodule https://github.com/shalomb/fetch-me  .config/submodules/fetch-me
( cd .config/submodules/fetch-me
  ln -svf  "$PWD"/fetch-me "$BINDIR"
)

# packer.nvim was deprecated in favor of lazy.nvim
# Migration completed in commit 1c7ec9d
