#!/bin/bash

# SYNOPSIS
#   git(1) aliases

_git_cmd=''
_git_args=()

gh_script=$BASH_SOURCE

#| gh - this screen
function gh {
  while read -r _ c _ r; do
    printf "  %-5s - %s\n" "$c" "$r"
  done < <( grep -iE '^#\|' "$gh_script" | sort ) | column -s - | "$PAGER"
}

function _git {
  local cmd="$1"; shift;
  local args=( "$@" )

  if (( ${#args[@]} == 0 )); then
    hist_index=$((HISTCMD-2))
    # Don't go messing around with history -p unless you
    # really know what it is doing.
    args=( $( history -p "!$hist_index:1*" &>/dev/null ) );
    # echo "args: ${args[@]} || ${#args[@]}"
    if [[ -n ${args[0]} ]]; then
      :;
    else
      args=( "${_git_args[@]}" )
    fi
  fi
  _git_args=( "${args[@]}" )

  command git "$cmd" "${args[@]}"
}

#| ga - git add
function ga  { _git "add"      "$@"; }
#| gd - git diff -b -w
function gd  { _git "diff" -b -w "$@"; }
#| gl - git lg
function gl  { _git "lg"       "$@"; }
#| gls - git ls
function gls { _git "ls" "$@"; }
#| glp - git lgp
function glp { _git "lgp"      "$@"; }
#| gp - git pull
function gp  { [[ $# = 0 ]] && set -- origin $(git branch | awk '/*/{print $2}'); command git pull "$@"; }
#| gP - git push
function gP  { [[ $# = 0 ]] && set -- origin $(git branch | awk '/*/{print $2}'); command git push "$@"; }
#| gs - git st --short
function gs  { _git "st" --short "$@"; }

#| gb - git branch
function gb  {
  _git "branch"   "$@";
  old_branch=$(git branch | awk '/*/{print $2}');
}

#| gco - git checkout
function gco {
  if [[ $# == 0 ]]; then
    if [[ ${old_branch-} ]]; then
      set -- "$old_branch"
    else
      set -- "develop"
    fi
  fi
  old_branch=$(git branch | awk '/*/{print $2}');
  _git "checkout" "$@";
}

# gcm - git commit -m
function gcm {
  local args=( "$@" )

  if (( ${#args[@]} == 0 )); then
    git commit
  else
    if [[ ${args[0]} != '-'* ]]; then
      args=( "$@" )
    fi
    git commit -m "${args[*]}"
  fi
}

#| g - git
    alias g=git
complete -o bashdefault -o default -o nospace -F __git_wrap__git_main g

#| gca - ga; gcm
  alias gca='ga; gcm '
#| gpom - git push origin master
 alias gpom='git push origin master'
#| gk - gitk --all
   alias gk='gitk --all &'
#| gx - gitx --all
   alias gx='gitx --all'

